title : mngch
tagline: mongocharger
author :
  name : Sebastian
  email : blah@email.test
  github : mngch
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

