title : mngch
tagline: mongocharger

author :
  name : Sebastian
  email : blah@email.test
  github : mngch
  twitter : rauchenderhund
  feedburner :

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

